name: Silpion Craft-Night example
on:
  pull_request:
      types: [ opened, edited, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print something
        run: ls
